### ISSUE TITLE
Write to log file instead in case backendless cannot be reached

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/token-burn-listener#9]
https://github.com/aeternity/token-burn-listener/blob/eb171d8d7ed6f1c09053a140c4ed858359509e34/server.js#L157

If this is the production code, we should definitely add a logfile write at this point, or else the missed event will will go completely unnoticed.

**Comment by dadaphl** [comment]
A file for logging is of no use because of our deployment setup. We would have no convenient way to gather it.

I propose to use Sentry.io. I just set up an account, send you an invite and create a PR soon for the integration.

**Comment by dadaphl** [comment]
fixed by #10
